---
- hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Install Security Updates
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      loop:
        - openssl
        - openssh
      ignore_errors: true # Error handling, make sure if a node fails the other nodes will continue with the next tasks
    
    - name: Check if docker is installed
      ansible.builtin.command: docker --version
      register: docker_check
      ignore_errors: true # Error handling, make sure if a node fails the other nodes will continue with the next tasks
    
    - name: Display docker check result
      ansible.builtin.debug:
        msg: "Docker is installed"
        var: docker_check
    
    - name: Install Docker if not present
      ansible.builtin.apt:
        name: docker.io
        state: present
      when: docker_check.failed

      # TASK TO SHOW FAILED_WHEN CONDITION
    - name: Check if a file exists
      ansible.builtin.command: ls /tmp/some_random_file
      register: file_check
      failed_when: 
      - file_check.rc == 0 # This will make the task fail if the file exists, just for demonstration purposes
      - '"No such file or directory" not in file_check.stdout' # This will make the task fail if the error is not "No such file or directory"